name: Build

on:
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        arch: [x86_64, aarch64, nrf52840]
    env:
      OPENTHREAD_SHA: ${{ github.event.client_payload.openthread_sha }}
      TARGET_OS: ${{ matrix.os }}
      TARGET_ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - run: ./.github/assets/entrypoint.sh

      - uses: actions/upload-artifact@v2
        with:
          name: openthread_${{ github.event.client_payload.openthread_short_sha }}_${{ matrix.os }}_${{ matrix.arch }}
          path: ./build.tar.gz
