name: Nightly build

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    runs-on: ubuntu-18.04

    steps:
      - name: Get latest OpenThread commit
        uses: actions/github-script@v2
        id: get-openthread-commit
        with:
          script: |
            const res = await github.repos.getCommit({
              owner: 'openthread',
              repo: 'openthread',
              ref: 'master'
            })

            const { sha } = res.data

            return {
              sha,
              short_sha: sha.substr(0, 7)
            }

      - name: Start build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          event-type: build
          client-payload: '{"openthread_sha": "${{ steps.get-openthread-commit.outputs.result.sha }}", "openthread_short_sha": "${{ steps.get-openthread-commit.outputs.result.short_sha }}"}'
